//通用模块存储方法
export const COMMON_UPDATA_USER_INFO = 'COMMON_UPDATA_USER_INFO' //更新用户信息
export const COMMON_INIT_USER_PERMISSIONS = 'COMMON_INIT_USER_PERMISSIONS' //初始化用户权限资源
export const COMMON_INIT_ROUTERS = 'COMMON_INIT_ROUTERS' //初始化路由
export const COMMON_INIT_ROLES = 'COMMON_INIT_ROLES' //初始化角色
export const COMMON_UPDATE_PAGE_SIZE = 'COMMON_UPDATE_PAGE_SIZE' //设置每页最大行数
export const COMMON_INIT_SYSTEM = 'COMMON_INIT_SYSTEM' //初始化系统配置

//前端用户存储方法
export const USER_INIT_DEVICES_OWNED = 'USER_INIT_DEVICES_OWNED'
export const USER_UPDATE_DEVICE_STATUS = 'USER_UPDATE_DEVICE_STATUS' //更新设备状态
export const USER_UPDATE_DEVICE_POSITION = 'USER_UPDATE_DEVICE_POSITION' //更新设备位置
export const USER_INIT_DEVICES = 'USER_INIT_DEVICES' //初始化设备状态和位置
export const USER_IS_SHOW_BUBBLE = 'USER_IS_SHOW_BUBBLE' //是否显示气泡
export const USER_SET_VISIBLES_FLAG = 'USER_SET_VISIBLES_FLAG' //设置隐藏显示属性
export const USER_SET_SELECT_DEVICE_ID = 'USER_SET_SELECT_DEVICE_ID' //设置选中的设备ID
export const USER_IS_TRACK_CENTER = 'USER_IS_TRACK_CENTER' //是否画面跟随
export const USER_ADD_DEVICE = 'USER_ADD_DEVICE' //添加设备
export const USER_SET_PLAY_ALARM_SOUND = 'USER_SET_PLAY_ALARM_SOUND' //设置播放报警声音
export const USER_SET_MAP_VALUES = 'USER_SET_MAP_VALUES' //设置map地图属性值
export const USER_SET_DEVICE_MARKERS_VISIBLE = 'USER_SET_DEVICE_MARKERS_VISIBLE' //设置设备maker是否可见
export const USER_SET_CONTROL_VALUE = 'USER_SET_CONTROL_VALUE' //设置轨迹回放控制按钮属性
export const USER_REMOVE_HISTORY_POSITIONS = 'USER_REMOVE_HISTORY_POSITIONS' //清理历史轨迹
export const USER_GET_HISTORY_POSITIONS = 'USER_GET_HISTORY_POSITIONS' //获取历史轨迹
export const USER_GET_GEOFENCES = 'USER_GET_GEOFENCES' //获取地理围栏
export const USER_HIDE_GEOFENCES = 'USER_HIDE_GEOFENCES' //隐藏地理围栏
export const USER_SET_SELECT_GEOFENCE = 'USER_SET_SELECT_GEOFENCE' //设置选中的围栏
export const USER_SET_SELECT_GEOFENCE_VALUE = 'USER_SET_SELECT_GEOFENCE_VALUE' //设置选中的围栏属性值
export const USER_UPDATE_SELECT_GEOFENCE = 'USER_UPDATE_SELECT_GEOFENCE' //修改选中的围栏属性

export const USER_SET_DRAW_ENABLE = 'USER_SET_DRAW_ENABLE' //设置开启 关闭绘制围栏事件
export const USER_SET_DRAW_GEOFENCE = 'USER_SET_DRAW_GEOFENCE' //设置绘制中的围栏
export const USER_SAVE_DRAW_GEOFENCE = 'USER_SAVE_DRAW_GEOFENCE' //保存绘制的围栏
export const USER_DELETE_SELECT_GEOFENCE = 'USER_DELETE_SELECT_GEOFENCE' //删除选中的围栏属性

export const USER_SET_MEASURE_ENABLE = 'USER_SET_MEASURE_ENABLE' //设置开启 关闭绘制围栏事件

export const USER_SET_MESSAGE_VALUE = 'USER_SET_MESSAGE_VALUE' //设置消息的条数
//export const USER_UPDATE_DEVICE_STATE='USER_UPDATE_DEVICE_STATE';//更新设备状态属性
export const USER_INIT_STATIC_DATA = 'USER_INIT_STATIC_DATA' //初始化静态数据
export const USER_SET_MARKER_VISIBLE = 'USER_SET_MARKER_VISIBLE' //设置设备marker是否可见
export const USER_INIT_GROUPS = 'USER_INIT_GROUPS' //初始化分组数据
export const USER_INIT_TREE_DATA = 'USER_INIT_TREE_DATA' //初始化分组设备属性数据
export const USER_LOOK_DEVICES_MOTION_STATE = 'USER_LOOK_DEVICES_MOTION_STATE' ////定时检查设备运动状态
export const USER_GET_EVENTS = 'USER_GET_EVENTS' //获取事件
export const USER_INIT_CUSTOMLAYERS = 'USER_INIT_CUSTOMLAYERS' //初始化自定义图层
export const USER_SET_CUSTOMLAYER_VALUE = 'USER_SET_CUSTOMLAYER_VALUE' //设置图层值
export const USER_SAVE_CUSTOMLAYER = 'USER_SAVE_CUSTOMLAYER' //保存自定义图层
export const USER_INIT_POIS = 'USER_INIT_POIS' //初始化兴趣点
export const USER_SET_POI_VALUE = 'USER_SET_POI_VALUE' //设置兴趣点值
export const USER_ADD_POI = 'USER_ADD_POI' //添加兴趣点

//系统管理后台存储方法
export const SYSTEM_TOGGLE_SIDEBAR = 'SYSTEM_TOGGLE_SIDEBAR' //菜单收缩控制

export const COMMON_UPDATE_EVENTS = 'COMMON_UPDATE_EVENTS' // update user events

export const INIT_USER_SETTING = "INIT_USER_SETTING"
export const UPDATE_USER_SETTING = "UPDATE_USER_SETTING"

export const ZOOM_IN = "ZOOM_IN"
export const ZOOM_OUT = "ZOOM_OUT"

export const SET_MAP_CENTER = "SET_MAP_CENTER"

export const SET_CUSTOM_MESSAGES = "SET_CUSTOM_MESSAGES"
export const GET_CUSTOM_MESSAGES = "GET_CUSTOM_MESSAGES"

export const SET_ALARM_SETTING_FLAG = "SET_ALARM_SETTING_FLAG"